### ISSUE TITLE
Rather generic name for a package meant for one team

### ISSUE THREAD

**Issue by tudormunteanu** [Doist/sqs-workers#14]
Hello,

If this package is meant to be used by the Doist only, it would be neater to give it a corresponding namespace, like `sqs-workers`. This would allow other developers to actually publish generic SQS worker libraries. Otherwise this is a bit like squatting.

Thanks in advance!

**Comment by goncalossilva** [comment]
Hi @tudormunteanu, thanks for pointing this out! To be honest, there is nothing specific to Doist in this project other than the note in the README. It was born out of internal needs, but that's applicable to most OSS projects. [We're confident others are using it, too!](https://github.com/Doist/sqs-workers/pull/9) :blush:

Have you faced a specific problem in trying to use it?
