### ISSUE TITLE
getresponse() got an unexpected keyword argument 'buffering'

### ISSUE THREAD

**Issue by swetha123-penta** [Doist/sqs-workers#3]

**Comment by swetha123-penta** [comment]
File "/home/swetha/venv/flaskproj/lib/python3.6/site-packages/urllib3/connectionpool.py", line 377, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

**Comment by imankulov** [comment]
Frankly, quite hard to understand what went wrong from such a concise report. From what I can see though, the problem may be related with using an outdated version of urllib3, and this issue can be related: https://github.com/urllib3/urllib3/issues/301

I'm closing this issue down. Meanwhile, feel free to reopen it with more details: how do yo reproduce the issue (which workers you run, or functions you call, etc), and which is your current stack (Python version as well as versions of installed packages as shown by `pip freeze`).

Cheers!
