### ISSUE TITLE
Support for arbitrary SQS messages?

### ISSUE THREAD

**Issue by januszm** [Doist/sqs-workers#5]
Hi. I came across this project because I am looking for a solution that will allow to run an execution pool (workers) that can process tasks from any AWS SQS queues with little effort. I mean queues that were not created by the application but are already present in AWS. These are e.g. various types of notifications from AWS systems, such as the creation of a file in S3.

I saw this:
> Unless you are the part of the Doist development team, you most likely don't need it. It's something opinionated, built out of our own internal needs and probably provides little value for outside developers.

But I still hoped that this package allows for "just processing SQS messages".

I tried this script:
```python
from sqs_workers import SQSEnv, create_standard_queue
sqs = SQSEnv()
import sdb

queue = sqs.queue("my_queue")

@queue.processor("process_blabla")
def process_blabla(*args):
    sdb.set_trace()
    pass

queue.process_queue()
```

But I only see:
```
UserWarning: Error while processing my_queue.None
```

from:
```python
def process_message_fallback(self, message):
    warnings.warn(
        "Error while processing {}.{}".format(self.name, get_job_name(message))
    )
    return False
```

```python
def get_job_name(message):
    attrs = message.message_attributes or {}
    return (attrs.get("JobName") or {}).get("StringValue")
```

Question: Is this project meant to support arbitrary SQS messages, or only those that have a special format that you use in your projects? e.g. mentioned `"JobName"`

**Comment by imankulov** [comment]
Sorry for the delayed response, @januszm. Not sure if it's still relevant, but replying anyway.

To process raw messages, you need to pass a RawQueue attribute to the `queue` call. The whole code can look like this.


```python
from sqs_workers import RawQueue, SQSEnv, create_standard_queue
sqs = SQSEnv()
import sdb

queue = sqs.queue("my_queue", RawQueue)  # pass the queue constructor as a second argument

@queue.raw_processor()    # don't pass the job name, as it doesn't make sense
def process_blabla(message):   # no args, just a raw Message argument
    print(message.body)

queue.process_queue()
```


- [Here we outlined it in more details](https://github.com/Doist/sqs-workers#raw-queues)
- [Here's is the documentation for the message object](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sqs.html#message)

**Comment by januszm** [comment]
Thank you @imankulov  !!!
