### ISSUE TITLE
How well can sqs-workers scale?

### ISSUE THREAD

**Issue by utkarshyadavin** [Doist/sqs-workers#8]
I have an SQS queue which might receives millions of tasks a day. Does this implementation of sqs-worker has the capability to scale to larger workloads without failure?

**Comment by vedavidhbudimuri** [comment]
@utkarshyadavin if you are asking about the throughput that SQS can offer then you can check the SQS limits page mentioned below 

https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-quotas.html

**Comment by imankulov** [comment]
Thanks for the link, @vedavidhbudimuri!

@utkarshyadavin, scalability of the solution based on SQS workers, doesn't depend on the library. You can scale processing horizontally by running multiple instances of workers.
